### PR TITLE
Add DE Translation

### PR DESCRIPTION
**Pull request by stefanfoulis**
And include locale for packaging.

### CODE REVIEW

**Comment by stefanfoulis** [comment]
@carljm could you re-trigger the travis build? That one thing that failed was probably a transient error.

**Comment by brad** [comment]
@stefanfoulis I'm on it

**Comment by brad** [comment]
@stefanfoulis I reran the build three times and it threw the same error each time :confused:

**Comment by stefanfoulis** [comment]
@brad I don't think the failing testcase has anything to do with this PR. Maybe some change in pip or pypy3?

**Comment by brad** [comment]
@stefanfoulis Agreed, thanks for the translations!

**Pull request merged**
